apiVersion: v1
kind: Service
metadata:
  name: perfect-agent-api
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app: perfect-agent-api
  ports:
    - port: {{ .Values.service.apiPort }}
      targetPort: 8000
      name: http
